version: '3.5'

services:
  nb_redis:
    image: 'bitnami/redis:latest'
    hostname: nb_redis
    volumes:
      - nb_redis:/data
    container_name: nb_redis
    command: redis-server --requirepass ${REDIS_PASS} --appendonly no --save ""
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - nb

  nb_redis_commander:
    container_name: nb_redis_commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: nb_redis
      REDIS_HOST: nb_redis
      REDIS_PORT: nb_redis:${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASS}
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - nb
    depends_on:
      - nb_redis

  nb_postgres:
    container_name: nb_postgres
    image: 'postgres:latest'
    restart: always
    environment:
      - DATABASE_URL=${POSTGRES_DATABASE_URL}
    volumes:
      - nb_postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - nb

networks:
  nb:
    name: nb

volumes:
  nb_redis:
  nb_postgres:
